### ISSUE TITLE
no openblas 0.2.19 builds for Linux.

### ISSUE THREAD

**Issue by zym1010** [conda-forge/scipy-feedstock#39]
See the title. When I do `conda install -c conda-forge openblas=0.2.19 scipy=0.18.1`, the scipy will fall back to the one in defaults channel. After looking around files on anaconda cloud, seems that openblas 0.2.19 builds for Linux are missing. Thanks.

**Comment by jakirkham** [comment]
Yeah, it appears the build failed. Seems like a new version of `numpy` came out on `defaults`. Instead of respecting channel priority, `conda` pulled in the `defaults` copy of `numpy` that was linked to `mkl`. As `scipy` here is linked to `openblas`, there was a clash that resulted in test failures. Will look at updating `numpy` and then come back to this. Thanks for the report.

cc @msarahan

**Comment by jakirkham** [comment]
Seems we already have the new `numpy` packaged. There were some timing issues in terms of getting it and `scipy` pinned. Maybe we can just restart the failed CircleCI build. Have done so. Please let me know if that still doesn't fix it. FYI might be a few hours before it completes.

**Comment by zym1010** [comment]
@jakirkham thanks! wonder if those CI companies can allow more flexible timing for conda-forge...

**Comment by zym1010** [comment]
Seems working now.

**Comment by jakirkham** [comment]
Yep, was just about to say that. Beat me to it. 😜

**Comment by jakirkham** [comment]
> wonder if those CI companies can allow more flexible timing for conda-forge...

Could you elaborate a bit? Not entirely sure in which you are thinking this would help.

**Comment by zym1010** [comment]
@jakirkham I just mean having longer time limit on those conda-forge jobs...
